<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Inventory Report - Dayana Enterprises</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #4CAF50; color: white; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h1 { margin-bottom: 5px; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Dayana Enterprises</h1>
        <h3>Inventory Stock Report</h3>
        <p>Date: {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Code</th>
                <th>Item</th>
                <th>Category</th>
                <th class="text-right">Cost Price</th>
                <th class="text-right">Selling Price</th>
                <th class="text-center">Stock</th>
                <th class="text-right">Value</th>
            </tr>
        </thead>
        <tbody>
            @foreach($items as $item)
            <tr>
                <td>{{ $item->item_code }}</td>
                <td>{{ $item->item_name }}</td>
                <td>{{ $item->category->name ?? '-' }}</td>
                <td class="text-right">Rs. {{ number_format($item->cost_price, 2) }}</td>
                <td class="text-right">Rs. {{ number_format($item->selling_price, 2) }}</td>
                <td class="text-center">{{ $item->stock_quantity }}</td>
                <td class="text-right">Rs. {{ number_format($item->stock_value, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th colspan="6" class="text-right">Total Stock Value:</th>
                <th class="text-right">Rs. {{ number_format($items->sum('stock_value'), 2) }}</th>
            </tr>
        </tfoot>
    </table>

    <p style="margin-top: 30px;">Generated by: {{ auth()->user()->name ?? 'System' }}</p>
</body>
</html>